### ISSUE TITLE
Add keyboard configuration option

### ISSUE THREAD

**Issue by mojo586** [delta1512/BOINCOS#12]
Gave this a quick try today (minmal) and it looks good. Maybe worth adding an option to allow users to configure their keyboard layout and potentially other locale options.

**Comment by delta1512** [comment]
I've planned this feature for both both spins, they will come in the BOINC OS helper whenever they are developed (hopefully v2.2).

**Comment by delta1512** [comment]
The BOINC OS Helper has been packed and tested with locale, keyboard and hostname changing tools, this upgrade will be implemented within the next version of the Minimal Spin. [Latest commit](https://github.com/delta1512/BOINCOS/commit/670e8361019abd98f292698fe6105c10ba2d423e)
