### ISSUE TITLE
[Website] 64-bit text is off by 10 pixels in downloads section

### ISSUE THREAD

**Issue by jorkermc** [delta1512/BOINCOS#13]
Maybe use top: -40px; instead of -30? (In the stylesheet)

**Comment by jorkermc** [comment]
![boincoswebsitescreenshot](https://user-images.githubusercontent.com/11705615/35771496-9fe4456e-093e-11e8-9c19-830e156062dc.png)
Screenshot for reference

**Comment by jorkermc** [comment]
By the way the text is selectable for the disabled Full Package Distro download link

**Comment by delta1512** [comment]
@jorkermc Can you please post browser specifications. Thanks.

**Comment by jorkermc** [comment]
Firefox Quantum 58.0.1 (64 bit)

**Comment by Aurailus** [comment]
Fixed in the latest commit.
